# Generated by Django 4.2.4 on 2023-11-13 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VetClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('day', models.CharField(max_length=250)),
                ('humidity', models.CharField(max_length=250)),
                ('temperature', models.CharField(max_length=250)),
                ('sickness', models.CharField(max_length=250)),
                ('diagnose', models.CharField(max_length=250)),
                ('img', models.ImageField(null=True, upload_to='images_uploaded')),
                ('video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
        ),
        migrations.CreateModel(
            name='VetUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
            ],
        ),
    ]
