# Generated by Django 4.2.4 on 2023-11-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetclient',
            name='video',
        ),
    ]
