# Generated by Django 4.2.4 on 2023-11-15 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0003_vetusers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetclient',
            name='vet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vet.vetusers'),
            preserve_default=False,
        ),
    ]
