# Generated by Django 4.2.4 on 2023-11-15 13:30

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('img', models.TextField()),
                ('comment_img', models.TextField()),
                ('comment', models.CharField(max_length=400)),
                ('create_at', models.DateField()),
                ('delivered', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='delivered.deliverusers')),
            ],
        ),
    ]
