# Generated by Django 4.2.4 on 2023-11-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivered', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivered',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
