# Generated by Django 4.2.4 on 2023-11-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivered', '0003_delivered_comment_img_alter_delivered_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivered',
            name='comment_img',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='delivered',
            name='img',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
