# Generated by Django 4.2.4 on 2023-11-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivered', '0004_alter_delivered_comment_img_alter_delivered_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverusers',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
