# Generated by Django 4.2.4 on 2023-11-15 05:47

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('delivered', '0005_deliverusers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivered',
            name='delivered',
            field=models.ForeignKey(default=1, on_delete=django.db.models.expressions.Case, to='delivered.deliverusers'),
            preserve_default=False,
        ),
    ]
